export const workExperienceData = [
    {
        id: 1,
        companyName: "Shane English School 夏恩英語",
        branchSchool: "Charlotte English School 夏綠蒂文理短期補習班",
        position: "ESL Teacher",
        dates: "March 2017 ~ Present",
        location: "New Taipei City, Taiwan",
        websiteName: "Shane English Official Website",
        website1: "https://shane.com.tw/",
        websiteName2: "Charlotte English Official Website",
        website2: "https://29863649.topschool.tw/Home/Main",
        jobDescription: "Taught elementary school and kindergerten aged children conversational English in Taiwan.",
    },

    {
        id: 2,
        companyName: "Wasabi Japanese Restaurant",
        branchSchool: null,
        position: "Waiter",
        dates: "June 2014 ~ December 2016",
        location: "Madison, WI",
        websiteName: "No longer in business",
        website1: null,
        jobDescription: "Waited on tables, processed payments and handled other customer service related tasks",
    },

    {
        id: 3,
        companyName: "Panda Express",
        branchSchool: null,
        position: "Chef",
        dates: "January 2013 ~ July 2014",
        location: "Appleton, WI",
        websiteName: "Company Website",
        website1: "https://www.pandaexpress.com/",
        jobDescription: "Prepared ingredients, cooked meals at a fast pace to meet customer demands and maintained a clean working environment",
    },

    {
        id: 4,
        companyName: "Caley Corporation",
        branchSchool: null,
        position: "Book Binder",
        dates: "June 2010 ~ August 2012",
        location: "Neenah, WI",
        websiteName: "No longer in business",
        website1: null,
        jobDescription: "During my summer breaks I used various machines to bind books together for customers, prepared shipments and handled various other tasks.",
    },
];